version: '3'

services:
  admin_backend:
   build:
     context: .
     dockerfile: Dockerfile
   command: 'python manage.py runserver 0.0.0.0:8020'
   ports:
     - 8020:8020
   extra_hosts:
     - "otherhost:172.168.0.20"

   volumes:
     - .:/app
   env_file:
     - ./.env.dev
   depends_on:
     - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=traincascade
      - POSTGRES_DB=admin

volumes:
  postgres_data: